bookstore_database:
  image: postgres:10.3-alpine
  ports:
    - '5432:5432'
  environment:
    POSTGRES_USER: 'admin'
    POSTGRES_PASSWORD: 'admin'
    POSTGRES_DB: 'bookstore'
  volumes:
    - ./init:/docker-entrypoint-initdb.d/
